development:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] %>
  username: root
  password: "test"
  database: chattr_dev
  pool: 5
test:
  adapter: mysql2
  encoding: utf8
  host: <%= ENV['MYSQL_PORT_3306_TCP_ADDR'] %>
  port: <%= ENV['MYSQL_PORT_3306_TCP_PORT'] %>
  username: root
  password: "test"
  database: chattr_test
  pool: 5